# ==============================================================================
# TANK 2D ONLINE - NETWORK CONFIGURATION (RADMIN LAN)
# ==============================================================================

# [1. DÀNH CHO CLIENT - KẾT NỐI TỚI SERVER]:
# Địa chỉ IP Radmin của máy chủ
server.host=26.173.79.163
server.port=8888

# [2. DÀNH CHO SERVER - CỔNG MỞ NỘI BỘ TRÊN MÁY BẠN]:
server.bind_port=8888
